sonar.organization=ksurahan-source
sonar.projectKey=ksurahan-source_hiob-contracts
sonar.projectName=hiob-contracts
sonar.sourceEncoding=UTF-8

sonar.sources=hiob_contracts,ts/src
sonar.exclusions=ts/src/**/*.test.ts
sonar.tests=tests,ts/src
sonar.test.inclusions=tests/**/*.py,ts/src/**/*.test.ts

sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml
sonar.javascript.lcov.reportPaths=ts/coverage/lcov.info
